export enum UserRole {
  ADMINISTRATOR = 'ADMINISTRATOR',
  STUDENT = 'STUDENT',
  TEACHER = 'TEACHER',
  RESPONSIBLE = 'RESPONSIBLE',
  HEAD_DEPARTMENT = 'HEAD_DEPARTMENT',
  TUTOR_GROUP = 'TUTOR_GROUP',
  ADMINISTRATION = 'ADMINISTRATION',
}
