version: '3.3'

services:
  pgsql:
    image: postgres:13
    ports:
      - '5432:5432'
    container_name: 'pgsql'
    restart: always
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ieszone_dev

  admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
